FROM node:20.12.2-alpine3.19 AS builder

RUN npm install -g pnpm

WORKDIR /app
COPY package.json pnpm-lock.yaml ./
RUN pnpm i

COPY . .
RUN npm run build

FROM node:20.12.2-alpine3.19
WORKDIR /app
COPY --from=builder /app/build build/
COPY package.json .
EXPOSE 3000

ENV NODE_ENV=production

CMD ["node", "build"]